### ISSUE TITLE
.

### ISSUE THREAD

**Issue by CodebenderCate** [EthanRBrown/rrad#4]
.

**Comment by EthanRBrown** [comment]
This repo does not contain _any_ PII.  It may contain your address, but to qualify as PII, it has to connect it somehow, directly or indirectly, with your identity.

I am happy to remove your address because what's one address less, and I don't want to cause a stir.  But if privacy is your concern, consider this: this issue is available for anyone to see, and if I make a commit that removes a single address, anyone who cares can now link your online identity (in the form of your GH profile) with your address which...seems worse to me?

Also, if you're concerned about your address (again, not associated with any part of your identity as a person) being "on the internet," please see the [OpenAddresses](https://openaddresses.io/) project and the original sources cited in the README; your address came from one of those sources, so you'll have to be contacting them as well.

**Comment by C4ph3RT1g3R** [comment]
Due to pending litigation I cannot discuss this in an open forum. Do you have a preferred method of contact that is private?

**Comment by EthanRBrown** [comment]
You can email me at ***@***.***

**Comment by C4ph3RT1g3R** [comment]
Providing my contact information ***@***.***
